language: android
android:
  components:
     # Update Android SDK Tools
    - tools

    - build-tools-23.0.2
    - android-21

    # Support library
    - extra-android-support
    - extra-android-m2repository
