language: android
jdk: oraclejdk8

android:
  components:
     # Update Android SDK Tools
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23	
    - add-on
    - extra
    - extra-android-support
    - extra-android-m2repository	
script:
   - ./gradlew build